### PR TITLE
fix: Deny access should land to the home page

### LINKED ISSUE #349: Deny access should land to the home page
Current message

failed to exchange code for token: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client","status_code":400}

### PR DESCRIPTION
**Pull request by serenahacker**
closes #349

Signed-off-by: serenahacker <serenahacker@gmail.com>

### CODE REVIEW

**Review by talwinder50 — APPROVED** [review]

File: cmd/login-consent-server/main.go [hunk 1]
```diff
@@ -417,15 +417,16 @@ func (c *consentServer) rejectConsentRequest(w http.ResponseWriter, req *http.Re
...
+	_, err := c.hydraClient.Admin.RejectConsentRequest(consentDeniedRequest)
 	if err != nil {
 		fmt.Fprint(w, err.Error())
 		w.WriteHeader(http.StatusInternalServerError)
 
 		return
 	}
 
-	http.Redirect(w, req, consentDenyResponse.Payload.RedirectTo, http.StatusFound)
+	http.Redirect(w, req, "https://issuer.trustbloc.local/", http.StatusFound)
```
Comment (rolsonquadras) [inline cmd/login-consent-server/main.go:429]: We shouldn't hardcode the url (this is a local deployment specific url).

**Review by rolsonquadras — CHANGES_REQUESTED** [review]

**Review by rolsonquadras — APPROVED** [review]
